### PR TITLE
revert strip and jsonstr

### PR DESCRIPTION
**Pull request by CohibAA**
revert strip and jsonstr

fix https://github.com/chris-belcher/joinmarket/issues/184#issuecomment-129602474 and 

```
  File "/home/cohibaa/joinmarket/lib/blockchaininterface.py", line 358, in do_HEAD
    txdata = json.loads(jsonstr)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
----------------------------------------
```

### CODE REVIEW

**Comment by domob1812** [comment]
I don't think this is the right patch.  Are you using `json-rpc` (as opposed to the new `json-rpc-socket`)?  I think the `strip()` should be part of the `BitcoinRpcCli` class instead.

I also believe that the `jsonstr` fix should be changed so that there is no `json.loads` below.

**Comment by CohibAA** [comment]
Sorry, I didn't mean to PR this, I thought I deleted it.

**Comment by domob1812** [comment]
Ah ok, no problem!  But if this fixes some real problem you have (which I can very well imagine, since the patch looks good in principle), it still makes sense to discuss a fix like this of my patch.

**Comment by CohibAA** [comment]
Will definitely let you know.

I _am_ trying to track down an [error](https://github.com/chris-belcher/joinmarket/issues/184#issue-100136080), and it was [suggested](https://github.com/chris-belcher/joinmarket/issues/184#issuecomment-129569679) it may be the lack of strip, but I haven't tested it yet.  BTW, I am using json-rpc, along with a couple other PRs, so I need to go do a bit more research.  Ideas welcome!

edit: I believe I misunderstood the config, I was thinking json-rpc-socket used bitcoin-cli and and json-rpc was using rpc calls.  Duh.

**Pull request closed without merging**
